const actionTypes = {
    "BUY_CAKE": "BUY_CAKE",
    "REFILL_CAKE_STOCK": "REFILL_CAKE_STOCK",
    "BUY_ICE_CREAM": "BUY_ICE_CREAM",
    "REFILL_ICE_CREAM_STOCK": "REFILL_ICE_CREAM_STOCK",
    "FETCH_POST_WITH_ID": "FETCH_POST_WITH_ID",
    "DO_SOMETHING_SYNC": "DO_SOMETHING_SYNC",
    "LOGIN": "LOGIN",
    "ORDER_FOOD_ANY_PLATFORM": "ORDER_FOOD_ANY_PLATFORM"
}




module.exports = actionTypes